# Generated by Django 5.2.1 on 2025-05-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='ingredients',
            field=models.TextField(default='Not specified'),
        ),
    ]
