# Generated by Django 5.2.1 on 2025-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothies', '0002_smoothie_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothie',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
